
server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/oauth2
#          public-key-location: classpath:certs
#          jws-algorithms: RSA512
#          jws-algorithms: RS256
#          jws-algorithms: HS256