server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
#          keycloak:
#            clientId: oauth2-client-app
#            clientSecret: IUcUxC5no8zlGo7aWGLzdBguo92BWCV3
#            clientName: oauth2-client-app
#            redirectUri: http://localhost:8081/login/v1/oauth2/code/keycloak
#            authorizationGrantType: authorization_code
#            clientAuthenticationMethod: client_secret_basic
#            scope: openid,profile,email
#            provider: keycloak
          keycloak:
            clientId: oauth2-client-app
            clientSecret: IUcUxC5no8zlGo7aWGLzdBguo92BWCV3
            clientName: oauth2-client-app
            redirectUri: http://localhost:8081/login/v1/oauth2/code/keycloak
            authorizationGrantType: client_credentials
            clientAuthenticationMethod: client_secret_basic
            provider: keycloak
#          keycloakWithPKCE:
#            clientId: oauth2-client-app2
#            clientSecret: 5oDNbSGwo1vx7fpyeSDz13QsO99cO0om
#            clientName: oauth2-client-app2
#            authorizationGrantType: authorization_code
#            scope: openid,profile
#            clientAuthenticationMethod: client_secret_basic
#            #                        clientAuthenticationMethod: none
#            redirectUri: http://localhost:8081/login/oauth2/code/keycloak
#            provider: keycloak
#
#          keycloak2:
#            clientId: oauth2-client-app3
#            clientSecret: tynI8eYUw4H1fJYxwLQ36XhFC1Ge1w1x
#            clientName: oauth2-client-app3
#            authorizationGrantType: implicit
#            scope: openid,profile
#            clientAuthenticationMethod: none
#            redirectUri: http://localhost:8081/home
#            provider: keycloak
        provider:
          keycloak:
            authorizationUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
            tokenUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token
            issuerUri: http://localhost:8080/realms/oauth2
            userInfoUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
            jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
            userNameAttribute: preferred_username
